# Generated by Django 5.2.1 on 2025-05-09 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='due_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
